name: Status_Recommender
recommender_class: Status_Recommender
params:
  NUM_HEADS: 4
  NUM_LAYERS: 2
  NUM_EPOCHS: 20
  EMBED_DIM: 128
  BATCH_SIZE: 128
  LR: 0.001
  DROPOUT: 0.1
  MAX_SEQ_LEN: 8
  USE_VAL_DISC: False
  VAL_DISCOUNT_RATIO: 0.1